import type {
  PriceData,
  TechnicalAnalysis,
  FundamentalAnalysis,
  LiquidityData,
  BotStatus,
  AccountInfo,
  Signal,
  AdminStats,
} from '@/types'

export const MOCK_PRICES: Record<string, PriceData> = {
  XAUUSD: {
    symbol: 'XAU/USD',
    price: 2345.50,
    bid: 2345.30,
    ask: 2345.70,
    change: 12.50,
    change_pct: 0.54,
    high: 2358.20,
    low: 2329.80,
    timestamp: new Date().toISOString(),
  },
  XAGUSD: {
    symbol: 'XAG/USD',
    price: 29.85,
    bid: 29.83,
    ask: 29.87,
    change: -0.15,
    change_pct: -0.50,
    high: 30.25,
    low: 29.60,
    timestamp: new Date().toISOString(),
  },
  WTI: {
    symbol: 'WTI',
    price: 78.45,
    bid: 78.43,
    ask: 78.47,
    change: 1.20,
    change_pct: 1.55,
    high: 79.10,
    low: 77.20,
    timestamp: new Date().toISOString(),
  },
  BRENT: {
    symbol: 'Brent',
    price: 82.30,
    bid: 82.28,
    ask: 82.32,
    change: 1.05,
    change_pct: 1.29,
    high: 83.00,
    low: 81.10,
    timestamp: new Date().toISOString(),
  },
  EURUSD: {
    symbol: 'EUR/USD',
    price: 1.0892,
    bid: 1.0891,
    ask: 1.0893,
    change: -0.0023,
    change_pct: -0.21,
    high: 1.0925,
    low: 1.0878,
    timestamp: new Date().toISOString(),
  },
  GBPUSD: {
    symbol: 'GBP/USD',
    price: 1.2748,
    bid: 1.2747,
    ask: 1.2749,
    change: 0.0045,
    change_pct: 0.35,
    high: 1.2785,
    low: 1.2710,
    timestamp: new Date().toISOString(),
  },
  BTCUSD: {
    symbol: 'BTC/USD',
    price: 62450.00,
    bid: 62445.00,
    ask: 62455.00,
    change: 850.00,
    change_pct: 1.38,
    high: 63200.00,
    low: 61580.00,
    timestamp: new Date().toISOString(),
  },
  DXY: {
    symbol: 'DXY',
    price: 104.85,
    bid: 104.84,
    ask: 104.86,
    change: 0.25,
    change_pct: 0.24,
    high: 105.10,
    low: 104.55,
    timestamp: new Date().toISOString(),
  },
}

export const MOCK_TECHNICAL: TechnicalAnalysis = {
  symbol: 'XAUUSD',
  timeframe: 'H1',
  overall_signal: 'buy',
  confidence: 78,
  confluence_score: 78,
  timeframes: {
    M15: {
      timeframe: 'M15',
      signal: 'buy',
      confidence: 72,
      indicators: [],
    },
    H1: {
      timeframe: 'H1',
      signal: 'buy',
      confidence: 82,
      indicators: [],
    },
    H4: {
      timeframe: 'H4',
      signal: 'buy',
      confidence: 75,
      indicators: [],
    },
    D1: {
      timeframe: 'D1',
      signal: 'neutral',
      confidence: 55,
      indicators: [],
    },
    W1: {
      timeframe: 'W1',
      signal: 'buy',
      confidence: 68,
      indicators: [],
    },
  },
  indicators: [
    { name: 'RSI(14)', value: 58.3, signal: 'buy', strength: 60 },
    { name: 'MACD', value: '12/26/9', signal: 'buy', strength: 75 },
    { name: 'EMA 20', value: 2338.50, signal: 'buy', strength: 80 },
    { name: 'EMA 50', value: 2325.80, signal: 'buy', strength: 85 },
    { name: 'EMA 200', value: 2298.40, signal: 'buy', strength: 90 },
    { name: 'Bollinger', value: 'Mid', signal: 'neutral', strength: 50 },
    { name: 'Stochastic', value: 65.4, signal: 'buy', strength: 65 },
    { name: 'ADX', value: 28.7, signal: 'buy', strength: 70 },
    { name: 'ATR', value: 18.5, signal: 'neutral', strength: 50 },
    { name: 'Volume', value: 'High', signal: 'buy', strength: 80 },
  ],
  schools: [
    { name: 'ICT (Smart Money)', name_ar: 'ICT (الأموال الذكية)', signal: 'buy', confidence: 85 },
    { name: 'Wyckoff', name_ar: 'وايكوف', signal: 'buy', confidence: 78 },
    { name: 'Elliott Wave', name_ar: 'موجات إليوت', signal: 'buy', confidence: 72 },
    { name: 'Dow Theory', name_ar: 'نظرية داو', signal: 'buy', confidence: 80 },
    { name: 'Supply & Demand', name_ar: 'العرض والطلب', signal: 'buy', confidence: 82 },
    { name: 'Fibonacci', name_ar: 'فيبوناتشي', signal: 'neutral', confidence: 55 },
    { name: 'Price Action', name_ar: 'حركة السعر', signal: 'buy', confidence: 77 },
    { name: 'Harmonic', name_ar: 'التوافقية', signal: 'neutral', confidence: 48 },
    { name: 'VSA (Volume)', name_ar: 'تحليل الحجم', signal: 'buy', confidence: 73 },
    { name: 'Gann Theory', name_ar: 'نظرية جان', signal: 'sell', confidence: 35 },
  ],
  entry_price: 2345.50,
  stop_loss: 2330.00,
  targets: [2360.00, 2375.00, 2395.00],
  timestamp: new Date().toISOString(),
}

export const MOCK_FUNDAMENTAL: FundamentalAnalysis = {
  symbol: 'XAUUSD',
  sentiment: 'bullish',
  events: [
    {
      id: '1',
      title: 'US CPI (YoY)',
      title_ar: 'مؤشر أسعار المستهلك الأمريكي',
      country: 'US',
      currency: 'USD',
      impact: 'high',
      datetime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      actual: null,
      forecast: '3.4%',
      previous: '3.5%',
      gold_impact: 'bullish',
    },
    {
      id: '2',
      title: 'Fed Chair Powell Speech',
      title_ar: 'خطاب رئيس الفيدرالي باول',
      country: 'US',
      currency: 'USD',
      impact: 'high',
      datetime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
      actual: null,
      forecast: '-',
      previous: '-',
      gold_impact: 'bearish',
    },
    {
      id: '3',
      title: 'US Jobless Claims',
      title_ar: 'طلبات إعانة البطالة',
      country: 'US',
      currency: 'USD',
      impact: 'medium',
      datetime: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
      actual: null,
      forecast: '215K',
      previous: '220K',
      gold_impact: 'bullish',
    },
    {
      id: '4',
      title: 'ECB Interest Rate Decision',
      title_ar: 'قرار أسعار الفائدة الأوروبي',
      country: 'EU',
      currency: 'EUR',
      impact: 'high',
      datetime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      actual: null,
      forecast: '4.00%',
      previous: '4.25%',
      gold_impact: 'bullish',
    },
    {
      id: '5',
      title: 'China Trade Balance',
      title_ar: 'الميزان التجاري الصيني',
      country: 'CN',
      currency: 'CNY',
      impact: 'medium',
      datetime: new Date(Date.now() + 30 * 60 * 60 * 1000).toISOString(),
      actual: null,
      forecast: '$72.5B',
      previous: '$68.4B',
      gold_impact: 'neutral',
    },
  ],
  news: [
    {
      id: '1',
      title: 'Gold Prices Rally as Fed Signals Rate Cuts',
      title_ar: 'الذهب يرتفع مع إشارات الفيدرالي لخفض الفائدة',
      summary: 'Gold futures surged to new highs as Fed officials signaled potential rate cuts in 2024',
      source: 'Reuters',
      url: '#',
      sentiment: 'bullish',
      published_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    {
      id: '2',
      title: 'Central Banks Continue Gold Buying Spree',
      title_ar: 'البنوك المركزية تواصل شراء الذهب',
      summary: 'Global central banks added record amounts of gold to reserves',
      source: 'Bloomberg',
      url: '#',
      sentiment: 'bullish',
      published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '3',
      title: 'Dollar Strengthens on Jobs Data',
      title_ar: 'الدولار يتقوى على بيانات الوظائف',
      summary: 'US dollar index rises as strong jobs data reduces rate cut expectations',
      source: 'CNBC',
      url: '#',
      sentiment: 'bearish',
      published_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '4',
      title: 'Geopolitical Tensions Support Safe Haven Demand',
      title_ar: 'التوترات الجيوسياسية تدعم الطلب على الملاذ الآمن',
      summary: 'Middle East tensions continue to drive demand for safe haven assets',
      source: 'MarketWatch',
      url: '#',
      sentiment: 'bullish',
      published_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '5',
      title: 'Gold Technical Analysis: Key Resistance at $2,360',
      title_ar: 'تحليل فني: مقاومة رئيسية عند 2360',
      summary: 'Technical analysts eye $2,360 as key resistance for gold bulls',
      source: 'Kitco',
      url: '#',
      sentiment: 'neutral',
      published_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    },
  ],
  timestamp: new Date().toISOString(),
}

export const MOCK_LIQUIDITY: LiquidityData = {
  symbol: 'XAUUSD',
  order_blocks: [
    {
      id: '1',
      level: 2328.50,
      direction: 'bullish',
      strength: 85,
      timeframe: 'H4',
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      is_active: true,
    },
    {
      id: '2',
      level: 2315.20,
      direction: 'bullish',
      strength: 72,
      timeframe: 'D1',
      created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      is_active: true,
    },
    {
      id: '3',
      level: 2368.40,
      direction: 'bearish',
      strength: 68,
      timeframe: 'H1',
      created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      is_active: true,
    },
    {
      id: '4',
      level: 2380.00,
      direction: 'bearish',
      strength: 90,
      timeframe: 'H4',
      created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      is_active: true,
    },
  ],
  fv_gaps: [
    {
      id: '1',
      top: 2342.80,
      bottom: 2340.50,
      direction: 'bullish',
      timeframe: 'M15',
      filled: false,
    },
    {
      id: '2',
      top: 2355.60,
      bottom: 2352.30,
      direction: 'bullish',
      timeframe: 'H1',
      filled: false,
    },
    {
      id: '3',
      top: 2325.40,
      bottom: 2322.10,
      direction: 'bearish',
      timeframe: 'H4',
      filled: true,
    },
  ],
  killzone: {
    name: 'New York Session',
    name_ar: 'جلسة نيويورك',
    active: true,
    start: '13:30',
    end: '22:00',
  },
  smart_money_bias: 'bullish',
  whale_alerts: [
    {
      id: '1',
      symbol: 'XAUUSD',
      side: 'buy',
      volume: 50.5,
      price: 2344.80,
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
    {
      id: '2',
      symbol: 'XAUUSD',
      side: 'buy',
      volume: 35.2,
      price: 2343.20,
      timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: '3',
      symbol: 'XAUUSD',
      side: 'sell',
      volume: 28.8,
      price: 2348.50,
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
  ],
}

export const MOCK_BOT_STATUS: BotStatus = {
  is_running: true,
  mode: 'semi-auto',
  active_symbols: ['XAUUSD', 'WTI'],
  last_signal: {
    id: 'sig_001',
    symbol: 'XAUUSD',
    direction: 'buy',
    timeframe: 'H1',
    entry_price: 2345.50,
    stop_loss: 2330.00,
    targets: [2360.00, 2375.00, 2395.00],
    confidence: 78,
    status: 'active',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  last_trade: null,
  total_signals_today: 7,
  total_trades_today: 3,
  started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
}

export const MOCK_ACCOUNT: AccountInfo = {
  balance: 10000.00,
  equity: 10245.50,
  margin: 580.20,
  free_margin: 9665.30,
  margin_level: 1765.4,
  daily_pnl: 245.50,
  daily_pnl_pct: 2.46,
  win_rate: 68.5,
  total_trades: 142,
  active_positions: 2,
}

export const MOCK_ADMIN_STATS: AdminStats = {
  total_users: 1247,
  active_subscriptions: 389,
  total_revenue: 28450,
  active_bots: 127,
  total_trades_today: 1842,
  win_rate: 71.3,
  new_users_today: 23,
}

export const SYMBOLS = [
  { value: 'XAUUSD', label: 'XAU/USD', labelAr: 'الذهب/دولار', tv: 'OANDA:XAUUSD' },
  { value: 'XAGUSD', label: 'XAG/USD', labelAr: 'الفضة/دولار', tv: 'OANDA:XAGUSD' },
  { value: 'WTI', label: 'WTI Oil', labelAr: 'النفط WTI', tv: 'TVC:USOIL' },
  { value: 'BRENT', label: 'Brent Oil', labelAr: 'النفط برنت', tv: 'TVC:UKOIL' },
  { value: 'EURUSD', label: 'EUR/USD', labelAr: 'يورو/دولار', tv: 'EURUSD' },
  { value: 'GBPUSD', label: 'GBP/USD', labelAr: 'جنيه/دولار', tv: 'GBPUSD' },
  { value: 'BTCUSD', label: 'BTC/USD', labelAr: 'بيتكوين/دولار', tv: 'BINANCE:BTCUSDT' },
]

export const TIMEFRAMES = [
  { value: 'M1', label: 'M1', labelAr: '1 د' },
  { value: 'M5', label: 'M5', labelAr: '5 د' },
  { value: 'M15', label: 'M15', labelAr: '15 د' },
  { value: 'M30', label: 'M30', labelAr: '30 د' },
  { value: 'H1', label: 'H1', labelAr: '1 س' },
  { value: 'H4', label: 'H4', labelAr: '4 س' },
  { value: 'D1', label: 'D1', labelAr: 'يومي' },
  { value: 'W1', label: 'W1', labelAr: 'أسبوعي' },
]
